# Defines a list of applications for satc
# Format: package_name:0
com.google.android.apps.tachyon:0
com.microsoft.teams:0
us.zoom.videomeetings:0
com.tencent.wemeet.app:0
com.alibaba.android.rimet:0
com.google.android.apps.maps:0
ru.yandex.yandexmaps:0
ru.yandex.yandexnavi:0
com.yandex.yango:0
com.ubercab:0
com.didiglobal.passenger:0
com.didiglobal.driver:0
com.sdu.didi.psnger:0
com.sdu.didi.gsui:0
com.sdu.didi.es.psngr:0
com.tencent.map:0
com.baidu.BaiduMap:0
com.didago.dida:0
com.didago.travel:0
com.autonavi.minimap:0
